version: "3.7"

services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=mysql+mysqlconnector://fastapi:fastapi@mysql_db/marketing_platform

  # db:
  #   image: postgres:12.1-alpine
  #   container_name: db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=fastapi
  #     - POSTGRES_PASSWORD=fastapi
  #     - POSTGRES_DB=fastapi
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketing_platform
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  # postgres_data:
  mysql_data:
