"""Added campaign image to campaign

Revision ID: 6720bfa93f76
Revises: 6ccbb4de4bcc
Create Date: 2023-10-15 16:13:07.739659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6720bfa93f76'
down_revision: Union[str, None] = '6ccbb4de4bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CampaignImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CampaignImage_id'), 'CampaignImage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CampaignImage_id'), table_name='CampaignImage')
    op.drop_table('CampaignImage')
    # ### end Alembic commands ###
