"""Added associated_influencer table

Revision ID: 6ccbb4de4bcc
Revises: 61b88329002c
Create Date: 2023-10-11 21:41:59.315251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccbb4de4bcc'
down_revision: Union[str, None] = '61b88329002c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Association_Influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['Influencer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Association_Influencers_id'), 'Association_Influencers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Association_Influencers_id'), table_name='Association_Influencers')
    op.drop_table('Association_Influencers')
    # ### end Alembic commands ###
