"""created_campaign_story_model

Revision ID: a476fbaff92b
Revises: dd4d26ee0851
Create Date: 2023-12-06 23:15:25.810767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a476fbaff92b'
down_revision: Union[str, None] = 'dd4d26ee0851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CampaignStory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_link', sa.String(length=500), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('thumb_path', sa.String(length=500), nullable=True),
    sa.Column('story_path', sa.String(length=500), nullable=True),
    sa.Column('inf_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['inf_id'], ['Influencer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CampaignStory_id'), 'CampaignStory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CampaignStory_id'), table_name='CampaignStory')
    op.drop_table('CampaignStory')
    # ### end Alembic commands ###
