"""image_url_field_added

Revision ID: db825550c548
Revises: a476fbaff92b
Create Date: 2024-01-16 22:10:27.430388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db825550c548'
down_revision: Union[str, None] = 'a476fbaff92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Influencer', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('Organization', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Organization', 'image_url')
    op.drop_column('Influencer', 'image_url')
    # ### end Alembic commands ###
