"""add_user_status

Revision ID: dd4d26ee0851
Revises: 6720bfa93f76
Create Date: 2023-11-20 23:26:43.673325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4d26ee0851'
down_revision: Union[str, None] = '6720bfa93f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('user_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'user_status')
    # ### end Alembic commands ###
